export function useHelpers() {
    const route = useRoute();

    function delay(timeout = 1000) {
        return new Promise((resolve) => setTimeout(resolve, timeout));
    }

    const isBlogArticle = computed(() => {
        return !pagePaths.includes(route.path);
    });

    const isListingPage = computed(() => {
        return listingPaths.includes(route.path);
    });

    const isThroughTheLensSlugPage = computed(() => {
        return route.path.startsWith("/through-the-lens/") && route.path !== "/through-the-lens";
    });

    const pagePaths = [
        "/",
        "/articles",
        "/vuejs",
        "/javascript",
        "/frontend",
        "/firebase",
        "/nodejs",
        "/backend",
        "/css",
        "/typescript",
        "/nestjs",
        "/nuxtjs",
        "/vscode",
        "/vite",
        "/langchain",
        "/python",
        "/nitro",
        "/ai",
        "/other",
        "/reactjs",
        "/the-keyboard-lab",
        "/the-keyboard-lab/lemon-milk",
        "/the-keyboard-lab/pastel-paws",
        "/the-keyboard-lab/retrograde",
        "/through-the-lens",
        "/through-the-lens/starlit-wonders",
        "/through-the-lens/liquid-cascades",
        "/through-the-lens/ocean-whispers",
        "/through-the-lens/urban-glow",
        "/through-the-lens/time-in-motion",
        "/through-the-lens/wild-horizons",
        "/through-the-lens/starlit-wonders/split-point-lighthouse",
        "/through-the-lens/starlit-wonders/watching-the-aurora-borealis",
        "/through-the-lens/starlit-wonders/aurora-borealis-over-the-great-ocean-road",
        "/through-the-lens/starlit-wonders/aurora-borealis-from-teddys-lookout",
        "/through-the-lens/starlit-wonders/star-trails-over-camel-rock",
        "/through-the-lens/starlit-wonders/star-trails-at-cape-schanck-lighthouse",
        "/through-the-lens/starlit-wonders/star-trails-at-cape-schanck",
        "/through-the-lens/starlit-wonders/milky-way-over-the-pinnacles",
        "/through-the-lens/starlit-wonders/milky-way-over-mount-donna-buang",
        "/through-the-lens/starlit-wonders/star-trails-at-pinnacles",
        "/through-the-lens/starlit-wonders/star-trails-at-pinnacles-phillip-island",
        "/through-the-lens/starlit-wonders/ss-speke-shipwreck",
        "/through-the-lens/starlit-wonders/the-shipwreck-ss-speke-phillip-island",
        "/through-the-lens/starlit-wonders/star-trails",
        "/through-the-lens/starlit-wonders/star-trails-at-uluru",
        "/through-the-lens/time-in-motion/flinders-february-sunset",
        "/through-the-lens/time-in-motion/melbourne-star",
        "/through-the-lens/time-in-motion/melbourne-city",
        "/through-the-lens/time-in-motion/balnarring-beach-pastel",
        "/through-the-lens/time-in-motion/bitola-from-above",
        "/through-the-lens/time-in-motion/balnarring-beach",
        "/through-the-lens/time-in-motion/cadillac-canyon",
        "/through-the-lens/time-in-motion/elwood-point-ormond",
        "/through-the-lens/time-in-motion/glasshouse-rocks",
        "/through-the-lens/time-in-motion/keyhole-rock",
        "/through-the-lens/time-in-motion/melbourne-train-trails",
        "/through-the-lens/time-in-motion/mordialloc",
        "/through-the-lens/time-in-motion/tenby-point-tree",
        "/through-the-lens/time-in-motion/yarra-boulevard",
        "/through-the-lens/wild-horizons/alfred-nicholas-gardens",
        "/through-the-lens/wild-horizons/stirling-range",
        "/through-the-lens/wild-horizons/alfred-nicholson-gardens",
        "/through-the-lens/wild-horizons/ballarat-boat-house",
        "/through-the-lens/wild-horizons/blue-boat-house",
        "/through-the-lens/wild-horizons/brighton-beach",
        "/through-the-lens/wild-horizons/cape-woolamai-walk",
        "/through-the-lens/wild-horizons/cape-woolamai",
        "/through-the-lens/wild-horizons/corio-bay-geelong-pier",
        "/through-the-lens/wild-horizons/galicica-viewpoint",
        "/through-the-lens/wild-horizons/george-bass-coastal-walk",
        "/through-the-lens/wild-horizons/george-bass-walk",
        "/through-the-lens/wild-horizons/kow-swamp",
        "/through-the-lens/wild-horizons/lonely-tree",
        "/through-the-lens/wild-horizons/perry-sandhills",
        "/through-the-lens/wild-horizons/mount-oberon-summit",
        "/through-the-lens/wild-horizons/mount-marta",
        "/through-the-lens/wild-horizons/on-the-edge-together",
        "/through-the-lens/wild-horizons/shelley-beach",
        "/through-the-lens/wild-horizons/shelly-beach",
        "/through-the-lens/wild-horizons/st-kilda-pier",
        "/through-the-lens/wild-horizons/san-remo",
        "/through-the-lens/wild-horizons/sunrise-at-uluru",
        "/through-the-lens/wild-horizons/tasman-drive-coast",
        "/through-the-lens/wild-horizons/teddys-lookout",
        "/through-the-lens/wild-horizons/the-cliffs",
        "/through-the-lens/wild-horizons/the-pinnacles",
        "/through-the-lens/wild-horizons/veternica-big-lake-pelister",
        "/through-the-lens/wild-horizons/whisky-bay",
        "/through-the-lens/wild-horizons/pillar-point",
        "/through-the-lens/wild-horizons/teddys-lookout-lorne",
        "/through-the-lens/wild-horizons/mundi-mundi-broken-hill",
        "/through-the-lens/urban-glow/bitola-forty-holy-martyrs-krkardash",
        "/through-the-lens/urban-glow/docklands-firelight-festival",
        "/through-the-lens/urban-glow/docklands-melbourne",
        "/through-the-lens/urban-glow/melbourne-batman-avenue",
        "/through-the-lens/urban-glow/melbourne-blue-hour-bridge",
        "/through-the-lens/urban-glow/melbourne-city-sunset-view",
        "/through-the-lens/urban-glow/melbourne-docklands-from-above",
        "/through-the-lens/urban-glow/melbourne-in-autumn",
        "/through-the-lens/urban-glow/melbourne-lightning-storm",
        "/through-the-lens/urban-glow/melbourne-new-years-eve",
        "/through-the-lens/urban-glow/melbourne-princes-bridge",
        "/through-the-lens/urban-glow/melbourne-swan-bridge-street",
        "/through-the-lens/urban-glow/melbourne-the-first-day-of-winter",
        "/through-the-lens/urban-glow/melbourne-the-lego-house",
        "/through-the-lens/urban-glow/photo-in-the-melbourne-city",
        "/through-the-lens/urban-glow/port-melbourn",
        "/through-the-lens/urban-glow/perth-from-the-pier",
        "/through-the-lens/ocean-whispers/balnarring-beach-wooden-wall",
        "/through-the-lens/ocean-whispers/balnarring-beach",
        "/through-the-lens/ocean-whispers/boat-and-sunrise",
        "/through-the-lens/ocean-whispers/bridge-water-bay",
        "/through-the-lens/ocean-whispers/broken-jetty-at-kororoit-creek",
        "/through-the-lens/ocean-whispers/cape-woolamai",
        "/through-the-lens/ocean-whispers/clifton-springs-oct",
        "/through-the-lens/ocean-whispers/dragon-head-mornington",
        "/through-the-lens/ocean-whispers/flinders-blowhole",
        "/through-the-lens/ocean-whispers/glasshouse-rocks-nsw",
        "/through-the-lens/ocean-whispers/great-ocean-road-the-twelve-apostles",
        "/through-the-lens/ocean-whispers/lord-arch-great-ocean-road",
        "/through-the-lens/ocean-whispers/mount-martha-mornington",
        "/through-the-lens/ocean-whispers/pinnacles-lookout-phillip-island",
        "/through-the-lens/ocean-whispers/pinnacles-phillip-island",
        "/through-the-lens/ocean-whispers/shelly-beach",
        "/through-the-lens/ocean-whispers/the-shelley-beach-portsea",
        "/through-the-lens/ocean-whispers/the-tree-at-tenby-point",
        "/through-the-lens/liquid-cascades/beauchamp-falls",
        "/through-the-lens/liquid-cascades/carrington-falls-nsw",
        "/through-the-lens/liquid-cascades/carrington-falls",
        "/through-the-lens/liquid-cascades/erskine-falls",
        "/through-the-lens/liquid-cascades/hopetoun-falls-great-ocean-road",
        "/through-the-lens/liquid-cascades/hopetoun-falls-walk",
        "/through-the-lens/liquid-cascades/hopetoun-falls",
        "/through-the-lens/liquid-cascades/otway-national-park-lower-kalimna-falls",
        "/through-the-lens/liquid-cascades/phantom-falls-otway-national-park",
        "/through-the-lens/liquid-cascades/sendang-gile-waterfalls",
        "/through-the-lens/liquid-cascades/the-falls-new-south-wales",
        "/through-the-lens/liquid-cascades/tiu-kelep-waterfalls",
        "/through-the-lens/liquid-cascades/toorongo-falls",
        "/through-the-lens/liquid-cascades/wannon-falls-scenic-reserve",
        "/get-in-touch",
        "/about-me",
        "/unsubscribe",
    ];

    const listingPaths = [
        "/articles",
        "/vuejs",
        "/javascript",
        "/frontend",
        "/firebase",
        "/nodejs",
        "/backend",
        "/css",
        "/typescript",
        "/nestjs",
        "/nuxtjs",
        "/vscode",
        "/vite",
        "/langchain",
        "/python",
        "/nitro",
        "/ai",
        "/other",
        "/reactjs",
    ];

    return {
        pagePaths,
        listingPaths,
        isBlogArticle,
        isListingPage,

        isThroughTheLensSlugPage,
        delay,
    };
}
