name: Deployment Prod

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Remove yarn.lock and node_modules
              run: |
                  rm -f yarn.lock
                  rm -rf node_modules

            - name: Run install root
              run: yarn install

            - name: Remove yarn.lock and node_modules in firebase functions folder
              run: |
                  cd functions
                  rm -f yarn.lock
                  rm -rf node_modules
                  cd ..

            - name: Run install in firebase functions folder
              run: |
                  cd functions
                  yarn install
                  cd ..

            - name: Create .env.prod file
              run: |
                  echo "::add-mask::${{ vars.SUBSCRIBE_TO_NEWSLETTERS_URL }}"
                  echo "SUBSCRIBE_TO_NEWSLETTERS_URL=${{ vars.SUBSCRIBE_TO_NEWSLETTERS_URL }}" >> .env.prod
                  echo "::add-mask::${{ vars.CONTACT_FORM_URL }}"
                  echo "CONTACT_FORM_URL=${{ vars.CONTACT_FORM_URL }}" >> .env.prod
                  echo "::add-mask::${{ vars.UNSUBSCRIBE_TO_NEWSLETTERS_URL }}"
                  echo "UNSUBSCRIBE_TO_NEWSLETTERS_URL=${{ vars.UNSUBSCRIBE_TO_NEWSLETTERS_URL }}" >> .env.prod
                  echo "::add-mask::${{ vars.RE_CAPTCHA_SITE_KEY }}"
                  echo "RE_CAPTCHA_SITE_KEY=${{ vars.RE_CAPTCHA_SITE_KEY }}" >> .env.prod
                  echo "::add-mask::${{ vars.GOOGLE_ANALYTICS_ID }}"
                  echo "GOOGLE_ANALYTICS_ID=${{ vars.GOOGLE_ANALYTICS_ID }}" >> .env.prod

            - name: Run Generate
              run: |
                  yarn generate:prod

            - name: Deploy to Netlify
              uses: jsmrcaga/action-netlify-deploy@v2.0.0
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
                  NETLIFY_DEPLOY_TO_PROD: true
                  build_directory: ".output/public"
                  install_command: "echo Skipping installing the dependencies"
                  build_command: "echo Skipping building the web files"
