name: Deployment Prod

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Remove yarn.lock and node_modules
              run: |
                  rm -f yarn.lock
                  rm -rf node_modules

            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command

            - name: Remove yarn.lock and node_modules in firebase functions folder
              run: |
                  cd functions
                  rm -f yarn.lock
                  rm -rf node_modules

            - name: Run install in firebase functions folder
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command

            - name: Go back to root folder
              run: |
                  cd ..

            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: generate:prod # will run `yarn generate:prod` command

            - name: Deploy to Netlify
              uses: jsmrcaga/action-netlify-deploy@v2.0.0
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_TO_PROD: true
                  build_directory: .output/public
