name: Deployment Prod

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.16.0"

            - name: Install dependencies
              run: yarn install

            - name: Build static site
              run: yarn generate:prod

            - name: Deploy to Netlify
              uses: jsmrcaga/action-netlify-deploy@v2.0.0
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_TO_PROD: true
                  build_directory: .output/public
