name: Deployment Prod

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Remove yarn.lock and node_modules
              run: |
                  rm -f yarn.lock
                  rm -rf node_modules

            - name: Run install root
              run: yarn install

            - name: Remove yarn.lock and node_modules in firebase functions folder
              run: |
                  cd functions
                  rm -f yarn.lock
                  rm -rf node_modules
                  cd ..

            - name: Run install in firebase functions folder
              run: |
                  cd functions
                  yarn install
                  cd ..

            - name: Create .env.prod file
              env:
                  SUBSCRIBE_TO_NEWSLETTERS_URL: ${{ vars.SUBSCRIBE_TO_NEWSLETTERS_URL }}
                  CONTACT_FORM_URL: ${{ vars.CONTACT_FORM_URL }}
                  UNSUBSCRIBE_TO_NEWSLETTERS_URL: ${{ vars.UNSUBSCRIBE_TO_NEWSLETTERS_URL }}
                  RE_CAPTCHA_SITE_KEY: ${{ vars.RE_CAPTCHA_SITE_KEY }}
                  GOOGLE_ANALYTICS_ID: ${{ vars.GOOGLE_ANALYTICS_ID }}
              run: |
                  echo "::add-mask::$SUBSCRIBE_TO_NEWSLETTERS_URL"
                  echo "SUBSCRIBE_TO_NEWSLETTERS_URL=$SUBSCRIBE_TO_NEWSLETTERS_URL" >> .env.prod
                  echo "::add-mask::$CONTACT_FORM_URL"
                  echo "CONTACT_FORM_URL=$CONTACT_FORM_URL" >> .env.prod
                  echo "::add-mask::$UNSUBSCRIBE_TO_NEWSLETTERS_URL"
                  echo "UNSUBSCRIBE_TO_NEWSLETTERS_URL=$UNSUBSCRIBE_TO_NEWSLETTERS_URL" >> .env.prod
                  echo "::add-mask::$RE_CAPTCHA_SITE_KEY"
                  echo "RE_CAPTCHA_SITE_KEY=$RE_CAPTCHA_SITE_KEY" >> .env.prod
                  echo "::add-mask::$GOOGLE_ANALYTICS_ID"
                  echo "GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID" >> .env.prod

            - name: Run Generate
              run: |
                  yarn generate:prod

            - name: Create redirect file
              run: |
                  echo "/2024/25/02/create-a-web-server-using-nitro-sqlite-and-typeorm    /2024/02/25/create-a-web-server-using-nitro-sqlite-and-typeorm" > .output/public/_redirects

            - name: Deploy to Netlify
              uses: jsmrcaga/action-netlify-deploy@v2.4.0
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
                  NETLIFY_DEPLOY_TO_PROD: true
                  build_directory: ".output/public"
                  install_command: "echo Skipping installing the dependencies"
                  build_command: "echo Skipping building the web files"
